version: '3.5'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    ports: 
      - 8096:8096
    volumes:
      - /path/to/jellyfin/config:/config
      - /path/to/jellyfin/cache:/cache
      - /path/to/jellyfin-media:/media
    restart: unless-stopped
